### ISSUE TITLE
Develop mode

### ISSUE THREAD

**Issue by masterdubs** [Ghardo/astor#4]
How do you run in node only to develop without compiling each time ?

**Comment by Ghardo** [comment]
Hi, 

if you are using the Bundler you can change the url 

```		
Windows: []*bootstrap.Window{{
   Homepage:       "http://localhost:8080",
   MessageHandler: handleMessages,
...
```

on localhost:8080 is a vue app running with `yarn serve`

**Comment by Ghardo** [comment]
I have an example here in my rgb control app

https://github.com/Ghardo/go-strip-color-v2/blob/master/main.go
